version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map container port 3000 to localhost port 3000
    volumes:
      - .:/app  # Mount current directory to /app in the container
    environment:
      FLASK_ENV: development  # Set Flask environment to development
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Define database password in the app's environment
      POSTGRES_USER: postgres  # Ensure it matches the database user setup
      POSTGRES_HOST: db  # Reference the db container's name as host
      POSTGRES_DB: fantasy_football_db
    depends_on:
      - db  # Ensure the db service starts before app

  db:
    image: postgres:latest
    ports:
    - "5433:5432"
    environment:
      POSTGRES_DB: fantasy_football_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
